server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      force: true
      charset: UTF-8

spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: RGJ-TRY
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.11.136.42:5432/postgres?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 342423

mybatis:
  type-aliases-package: model
  #指定位置扫描Mapper接口对应的XML文件 classpath:xml文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页插件
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: postgresql

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    enabled: true



